[package]
name = "orca-core"
version = "0.1.0"
edition = "2024"

[dependencies]
orca-platform = { path = "../orca-platform" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
toml = { workspace = true }
dirs = { workspace = true }
libc = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
