[package]
name = "orca-mcp"
version = "0.1.0"
edition = "2024"

[features]
test-utils = []

[dependencies]
orca-core = { path = "../orca-core" }
orca-platform = { path = "../orca-platform" }
serde_json = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
tempfile = { workspace = true }
